version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
  api:
    build: api/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  front:
    build: front/
    working_dir: /app/app
    command: yarn dev
    volumes: 
      - ./front/app:/app
    ports:
      - "8080:3000"
volumes:
  db_data: